@SuperHeroApp_HostAddress = https://localhost:7251

GET {{SuperHeroApp_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SuperHeroApp_HostAddress}}/weatherforecast

###


GET {{SuperHeroApp_HostAddress}}/weatherforecast

###
